- name: Flask project
  hosts: all
  become: yes
  tasks:
    - name: Git checkout the code
      unarchive:
        src: https://github.com/kmanika/interview_project.git
        dest: /home/ec2-user/
        remote_src: yes

    - name: Install dependencies
      pip:
        requirements: /home/ec2-user/flask_py/interview_project/requirements.txt
        executable: pip3

    - name: SystemD Configuration
      tempfile:
        src: /home/ec2-user/flask_py/interview_project/flask_py/helloworld.service
        dest: /etc/systemd/system/helloworld.service

    - name: Restart services
      systemd:
        name: helloworld
        state: restarted
        enabled: yes





